apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: digitalphoenixx/udagram-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80