apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          image: digitalphoenixx/udagram-api-user:v1
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: udagram-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: udagram-secret
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: udagram-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: udagram-secret
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  key: AWS_BUCKET
                  name: udagram-secret
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_REGION
                  name: udagram-secret
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  key: AWS_PROFILE
                  name: udagram-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: udagram-secret
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: URL
                  name: udagram-configmap
          ports:
            - containerPort: 8080
