
language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed digitalphoenixx/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user digitalphoenixx/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend digitalphoenixx/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy digitalphoenixx/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push digitalphoenixx/udagram-api-feed:v1
  - docker push digitalphoenixx/udagram-api-user:v1
  - docker push digitalphoenixx/udagram-frontend:v1
  - docker push digitalphoenixx/udagram-reverseproxy:v1